# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c228a04aeee81e81a4e6ad23f005c02d7f1e3860fbbf286e57e2525289a630f2bea2917a7de17cd91369cc7723aa3931b3d4eeb32b3bcefa2c162476dcc6d683

test:
  secret_key_base: 7455fb20317b9e986774ce88b39d49b78bc71cd7972e779c16e93299db6e42374916ec74ba2743a64f6ccac2c534e4b1eb11f88af1b111ebc977a0460bc21ac3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
